// Fast ALS building fragment shader - FlightGear 2024.1.x
//
// Keeps the stock FlightGear building lightmap path exactly where it matters:
// lightmap_r_factor / lightmap_r_color are the uniforms generated by the
// model-combined effect for lightmap-factor/lightmap-color n="0".
//
// v7: (a) haze base colour is computed per VERTEX (BLD_HAZE_IN_VERTEX), saving ~9 exp/pow
// per hazed pixel; (b) the lightmap texture is not fetched while lightmap factor is 0
// (daytime); (c) cheap weather/moon extras: wet walls, roof snow, moon-scaled night
// ambient (BLD_WET_SNOW). Requires the matching building-ALS.vert + building.eff.
// v6: the fog/haze is now a port of the stock ALS haze model (hazing.frag,
// applyHaze) so OSM-generated buildings fade in fog, rain, dusk and night
// exactly like terrain and basic models. Left out on purpose (GTX 1060 budget):
// the Noise2D/Noise3D fog structure and layer-edge blur (quality_level > 3),
// normal map, reflections, rain/snow overlays, secondary lights.
//
// Self-contained: does NOT need hazing.frag / noise.frag / filters linked.
// All helper names are prefixed with bld_ so they cannot clash with the
// stock functions if the effect happens to link them anyway.
#version 120

uniform sampler2D texture;
uniform sampler2D LightMapTex;

uniform int lightmap_enabled;
uniform int lightmap_multi;
uniform float lightmap_r_factor;
uniform vec3 lightmap_r_color;

// ALS atmosphere uniforms (same set the stock ALS model shaders use).
uniform float visibility;         // ground visibility (m)
uniform float avisibility;        // visibility above the haze layer (m)
uniform float hazeLayerAltitude;  // top of the haze layer (m ASL)
uniform float eye_alt;            // camera altitude (m ASL)
uniform float terminator;
uniform float terrain_alt;
uniform float overcast;
uniform float scattering;
uniform float cloud_self_shading;
uniform float air_pollution;
uniform float moonlight;             // 0 if unbound -> behaves exactly like v6
uniform float wetness;               // 0 if unbound -> no effect
uniform float bld_snow_level;        // set in building.eff; <= 1 means "no snow info"
uniform float bld_snow_thickness;

varying vec4 diffuse_term;
varying vec3 normal;
varying vec3 relPos;
varying float yprime_alt;   // written by building-ALS.vert
varying float mie_angle;    // written by building-ALS.vert
varying vec3  bld_hazeBase; // written by building-ALS.vert (haze colour at the vertex)

// Debug: 0 = normal, 1 = transmission (white = clear, black = fully hazed),
//        2 = haze color
#define FOG_DEBUG 0

// 1 = also run the stock filter_combined() tone/gamma stage. Only enable if
// terrain and buildings differ in overall tone AND the effect links the stock
// filter shader (otherwise the program will fail to link).
#define USE_FILTER_COMBINED 0

// 1 = haze base colour comes from the vertex shader (cheaper). 0 = old per-pixel path.
// Both files (.vert and .frag) must be replaced together; set 0 here to revert.
#define BLD_HAZE_IN_VERTEX 1

// 1 = wet walls in rain, snow on roofs, moon-scaled night ambient. 0 = v6 look.
#define BLD_WET_SNOW 1

// Visibility multiplier for tuning (>1 = clearer, <1 = hazier).
const float VIS_SCALE = 1.0;

const float BLD_TERMINATOR_WIDTH = 200000.0;
const float BLD_EARTH_RADIUS = 5800000.0;

const vec3 NIGHT_AMBIENT = vec3(0.09, 0.10, 0.14);   // 0 = kapalı

#if USE_FILTER_COMBINED == 1
vec3 filter_combined(in vec3 color);
#endif

float bld_trans;
vec3  bld_hazeOut;

// ALS fog function: exp(-d/D) at low altitude, exp(-d^2/D^2) very high up.
float bld_fog_func(in float targ, in float alt)
{
    targ = 1.25 * targ * smoothstep(0.04, 0.06, targ);
    float t2 = targ * targ;
    float t4 = t2 * t2;

    if (alt < 30000.0)
        return exp(-targ - t4);
    if (alt < 50000.0)
    {
        float m = (alt - 30000.0) / 20000.0;
        return m * exp(-t2 - t4) + (1.0 - m) * exp(-targ - t4);
    }
    return exp(-t2 - t4);
}

float bld_light_curve(in float x, in float a, in float b, in float c, in float d, in float e)
{
    x = x - 0.5;
    if (x > 30.0)  return e;
    if (x < -15.0) return 0.0;
    return e / pow(1.0 + a * exp(-b * (x - c)), 1.0 / d);
}

vec3 bld_hazeColor(in float lightArg)
{
    vec3 c;
    c.r = bld_light_curve(lightArg, 8.305e-06, 0.161, 4.827 - 3.0 * air_pollution, 3.04e-05, 1.0);
    c.g = bld_light_curve(lightArg, 3.931e-06, 0.264, 3.827, 7.93e-06, 1.0);
    c.b = bld_light_curve(lightArg, 1.330e-05, 0.264, 1.527 + 2.0 * air_pollution, 1.08e-05, 1.0);
    return c;
}

// Noise-free port of applyHaze() from the stock hazing.frag.
vec3 bld_applyHaze(in vec3 color, in float dist, in float ct, in float lightArg,
                   in float mie, in vec3 n, in vec3 lightDir,
                   in float visL, in float visA)
{
    float mvis = min(visL, visA);

    bld_trans = 1.0;
    bld_hazeOut = vec3(0.0);

    if (dist <= 0.04 * mvis)
        return color;

    float delta_z = hazeLayerAltitude - eye_alt;
    float distance_in_layer = 0.0;
    float delta_zv = 0.0;
    float vAltitude;
    float H;

    // Unbound uniforms read as 0: treat that as "no attenuation from it".
    float scat = (scattering > 0.0) ? scattering : 1.0;
    float css  = (cloud_self_shading > 0.0) ? cloud_self_shading : 1.0;
    float effective_scattering = min(scat, css);

    vec3 shadedFogColor = vec3(0.55, 0.67, 0.88);

    // Which part of the eye->fragment path lies inside the haze layer.
    if (delta_z > 0.0)
    {   // camera inside the layer
        if (ct < 0.0)
        {
            distance_in_layer = dist;
            vAltitude = min(distance_in_layer, mvis) * ct;
            delta_zv = delta_z - vAltitude;
        }
        else
        {
            H = dist * ct;
            distance_in_layer = (H > delta_z) ? dist / H * delta_z : dist;
            vAltitude = min(distance_in_layer, visL) * ct;
            delta_zv = delta_z - vAltitude;
        }
    }
    else
    {   // camera above the layer
        H = dist * -ct;
        if (H < -delta_z)
        {
            distance_in_layer = 0.0;
            delta_zv = 0.0;
        }
        else
        {
            vAltitude = H + delta_z;
            distance_in_layer = vAltitude / max(H, 0.001) * dist;
            vAltitude = min(distance_in_layer, visL) * (-ct);
            delta_zv = vAltitude;
        }
    }

    float transmission_arg = (dist - distance_in_layer) / visA
    + distance_in_layer / mvis;

    float eqColorFactor = 1.0 - 0.1 * delta_zv / mvis - (1.0 - effective_scattering);
    float transmission = bld_fog_func(transmission_arg, eye_alt);
    eqColorFactor = max(eqColorFactor, 0.2);

    float eShade = 1.0 - 0.9 * smoothstep(-BLD_TERMINATOR_WIDTH + terminator,
                                          BLD_TERMINATOR_WIDTH + terminator,
                                          yprime_alt);

#if BLD_HAZE_IN_VERTEX == 1
    vec3 hazeColor = bld_hazeBase;
#else
    vec3 hazeColor = bld_hazeColor(lightArg);
#endif
    float intensity = length(hazeColor);

    if (intensity > 0.0)
    {
        // Mie-like forward scattering for a low sun
        if (lightArg < 10.0)
        {
            float mie_magnitude = 0.5 * smoothstep(350000.0, 150000.0,
                                                   terminator - sqrt(2.0 * BLD_EARTH_RADIUS * terrain_alt));
            hazeColor = intensity * ((1.0 - mie_magnitude) + mie_magnitude * mie)
            * normalize(mix(hazeColor, vec3(0.5, 0.58, 0.65),
                            mie_magnitude * (0.5 - 0.5 * mie)));
        }

        intensity = length(hazeColor);

        // high altitude desaturation
        hazeColor = intensity * normalize(mix(hazeColor, intensity * vec3(1.0),
                                              0.7 * smoothstep(5000.0, 50000.0, eye_alt)));

        // blue hue of haze
        hazeColor.x *= 0.83;
        hazeColor.y *= 0.9;

        // additional blue in indirect light
        float fade_out = max(0.65 - 0.3 * overcast, 0.45);
        intensity = length(hazeColor);
        hazeColor = intensity * normalize(mix(hazeColor, 1.5 * shadedFogColor,
                                              1.0 - smoothstep(0.25, fade_out, eShade)));

        // blue hue for strong fogging
        hazeColor = intensity * normalize(mix(hazeColor, shadedFogColor,
                                              1.0 - smoothstep(0.5, 0.9, eqColorFactor)));

        // reduce haze intensity on shaded surfaces, terminator region only
        float shadow = mix(min(1.0 + dot(n, lightDir), 1.0), 1.0,
                           1.0 - smoothstep(0.1, 0.4, transmission));
        hazeColor = mix(shadow * hazeColor, hazeColor,
                        0.3 + 0.7 * smoothstep(250000.0, 400000.0, terminator));
    }

    // don't let the light fade out too rapidly
    float lArg = (terminator + 200000.0) / 100000.0;
    float minLightIntensity = min(0.2, 0.16 * lArg + 0.5);
    vec3 minLight = minLightIntensity * vec3(0.2, 0.3, 0.4);
    hazeColor *= eqColorFactor * eShade;
    hazeColor = max(hazeColor, minLight);

    bld_trans = transmission;
    bld_hazeOut = hazeColor;

    return mix(clamp(hazeColor, 0.0, 1.0), clamp(color, 0.0, 1.0), transmission);
}

void main()
{
    vec4 texel = texture2D(texture, gl_TexCoord[0].st);

    if (texel.a < 0.10)
        discard;

    vec3 N = normalize(normal);
    vec3 L = normalize(gl_LightSource[0].position.xyz);
    float NdotL = max(dot(N, L), 0.0);

    // ALS vertex shader supplies the non-directional ambient term in gl_Color
    // and the sun/directional term in diffuse_term.
    vec3 ambient = max(gl_Color.rgb, vec3(0.0));
    vec3 direct = max(diffuse_term.rgb, vec3(0.0)) * NdotL;
    //vec3 lighting = ambient + direct;
#if BLD_WET_SNOW == 1
    // brighter night ambient around full moon (moonlight = 0 when unbound -> unchanged)
    vec3 lighting = max(ambient + direct, NIGHT_AMBIENT * (1.0 + 0.6 * clamp(moonlight, 0.0, 1.0)));
#else
    vec3 lighting = max(ambient + direct, NIGHT_AMBIENT);
#endif

    vec3 mixedcolor = texel.rgb;

#if BLD_WET_SNOW == 1
    // wet walls are darker (wetness is 0 in dry weather)
    mixedcolor *= 1.0 - 0.3 * clamp(wetness, 0.0, 1.0);

    // roof snow, same altitude rule as the road shader (snow from snowlevel + 220 m up).
    // Nested uniform branches: dry/low areas skip everything.
    if (bld_snow_level > 1.0)
    {
        float snowAlt = relPos.z + eye_alt;
        if (snowAlt > bld_snow_level + 220.0)
        {
            vec3 upEC = normalize((gl_ModelViewMatrix * vec4(0.0, 0.0, 1.0, 0.0)).xyz);
            float roof = smoothstep(0.55, 0.85, dot(N, upEC));
            float mask = smoothstep(bld_snow_level, bld_snow_level + 200.0, snowAlt - 220.0);
            float thick = 0.2 + 0.8 * smoothstep(0.2, 0.8, 0.3 + 0.5 * bld_snow_thickness
                                                 + 0.0001 * (snowAlt - bld_snow_level));
            mixedcolor = mix(mixedcolor, vec3(0.95), roof * mask * thick);
        }
    }
#endif
    vec3 fragColor = mixedcolor * lighting;

    // ---------------------------------------------------------------------
    // STOCK BUILDING LIGHTMAP PATH
    // ---------------------------------------------------------------------
    if (lightmap_enabled >= 1 && lightmap_r_factor > 0.001)
    {
        vec4 lightmapTexel = texture2D(LightMapTex, gl_TexCoord[0].st);
        vec3 lightmapcolor = vec3(0.0);
        vec4 lightmapFactor = vec4(lightmap_r_factor);

        if (lightmap_multi > 0)
        {
            lightmapFactor *= lightmapTexel;
            lightmapcolor = lightmap_r_color * lightmapFactor.r;
        }
        else
        {
            lightmapcolor = lightmapTexel.rgb * lightmap_r_color * lightmapFactor.r;
        }

        // Emissive: not multiplied by the dark nighttime diffuse lighting,
        // but it is hazed below like everything else.
        fragColor = max(
            fragColor,
            lightmapcolor * gl_FrontMaterial.diffuse.rgb *
            smoothstep(0.0, 1.0, mixedcolor * 1.5 + lightmapcolor * 4.5)
        );
    }

    // ---------------------------------------------------------------------
    // ALS HAZE
    // ---------------------------------------------------------------------
    float dist = max(length(relPos), 0.001);
    float ct = relPos.z / dist;
    float lightArg = (terminator - yprime_alt) / 100000.0;

    // Fallback if the ALS visibility uniforms are not bound in this pass:
    // derive visibility from the fixed-function fog density.
    float visG = (gl_Fog.density > 0.0) ? 2.5 / gl_Fog.density : 1.0e5;
    float visL = ((visibility  > 1.0) ? visibility  : visG) * VIS_SCALE;
    float visA = ((avisibility > 1.0) ? avisibility : visL) * VIS_SCALE;

    vec3 finalColor = bld_applyHaze(fragColor, dist, ct, lightArg, mie_angle,
                                    N, L, visL, visA);

    #if USE_FILTER_COMBINED == 1
    finalColor = filter_combined(finalColor);
    #endif

    #if FOG_DEBUG == 1
    gl_FragColor = vec4(vec3(bld_trans), 1.0);
    return;
    #elif FOG_DEBUG == 2
    gl_FragColor = vec4(bld_hazeOut, 1.0);
    return;
    #endif

    gl_FragColor = vec4(finalColor, texel.a);
}
